### ISSUE TITLE
v6 Job Type create breaks on missing tags

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1307]
If you try to POST a v6 Job Type without the optional `manifest.job.tags` member a 500 server error is returned. The submitted job type:

```
{
    "docker_image": "nvidia/cuda:7.0-cudnn4-runtime",
    "manifest": 
    {
	  "seedVersion": "1.0.0",
	  "job": {
	    "name": "gpu-test",
	    "jobVersion": "1.0.0",
	    "packageVersion": "1.0.0",
	    "title": "GPU Test",
	    "description": "Validates GPU accessibility by executing nvidia-smi",
	    "maintainer": {
	      "name": "Jonathan Meyer",
	      "organization": "Applied Information Sciences",
	      "email": "jon@gisjedi.com"
	    },
	    "timeout": 3600,
	    "interface": {
	      "command": "nvidia-smi"
	    },
	    "resources": 
		    {
		    	"scalar": [
		    		{ "name": "gpus", "value": 1.0 }
		    		]

		    }
	  }
	}
}
```

The resulting stack trace in the web server:

```
[Tue Aug 28 20:09:17.382960 2018] [:error] [pid 12] 2018-08-28 20:09:17 ERROR [root(21)] Exception handling request for /service/scale/api/v6/job-types/.
[Tue Aug 28 20:09:17.382984 2018] [:error] [pid 12] Traceback (most recent call last):
[Tue Aug 28 20:09:17.382988 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Aug 28 20:09:17.382990 2018] [:error] [pid 12]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Aug 28 20:09:17.382993 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Tue Aug 28 20:09:17.382995 2018] [:error] [pid 12]     return view_func(*args, **kwargs)
[Tue Aug 28 20:09:17.382997 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
[Tue Aug 28 20:09:17.383000 2018] [:error] [pid 12]     return self.dispatch(request, *args, **kwargs)
[Tue Aug 28 20:09:17.383002 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
[Tue Aug 28 20:09:17.383004 2018] [:error] [pid 12]     response = self.handle_exception(exc)
[Tue Aug 28 20:09:17.383006 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
[Tue Aug 28 20:09:17.383008 2018] [:error] [pid 12]     self.raise_uncaught_exception(exc)
[Tue Aug 28 20:09:17.383010 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
[Tue Aug 28 20:09:17.383012 2018] [:error] [pid 12]     response = handler(request, *args, **kwargs)
[Tue Aug 28 20:09:17.383014 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/rest_framework/generics.py", line 244, in post
[Tue Aug 28 20:09:17.383036 2018] [:error] [pid 12]     return self.create(request, *args, **kwargs)
[Tue Aug 28 20:09:17.383051 2018] [:error] [pid 12]   File "/opt/scale/job/views.py", line 145, in create
[Tue Aug 28 20:09:17.383054 2018] [:error] [pid 12]     return self.create_v6(request)
[Tue Aug 28 20:09:17.383056 2018] [:error] [pid 12]   File "/opt/scale/job/views.py", line 325, in create_v6
[Tue Aug 28 20:09:17.383058 2018] [:error] [pid 12]     configuration=configuration)
[Tue Aug 28 20:09:17.383060 2018] [:error] [pid 12]   File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
[Tue Aug 28 20:09:17.383061 2018] [:error] [pid 12]     return func(*args, **kwargs)
[Tue Aug 28 20:09:17.383063 2018] [:error] [pid 12]   File "/opt/scale/job/models.py", line 2623, in create_job_type_v6
[Tue Aug 28 20:09:17.383066 2018] [:error] [pid 12]     JobTypeTag.objects.update_job_type_tags(job_type, manifest)
[Tue Aug 28 20:09:17.383068 2018] [:error] [pid 12]   File "/opt/scale/job/models.py", line 4056, in update_job_type_tags
[Tue Aug 28 20:09:17.383080 2018] [:error] [pid 12]     tags = manifest.get_tags()
[Tue Aug 28 20:09:17.383082 2018] [:error] [pid 12]   File "/opt/scale/job/seed/manifest.py", line 125, in get_tags
[Tue Aug 28 20:09:17.383084 2018] [:error] [pid 12]     return self.get_job()['tags']
[Tue Aug 28 20:09:17.383086 2018] [:error] [pid 12] KeyError: u'tags'
```

**Comment by mikenholt** [comment]
Fixed with #1309
