### ISSUE TITLE
Push data through geoint/read-bytes for scale

### ISSUE THREAD

**Issue by soccerjustinh1** [ngageoint/scale#649]
@gisjedi I have have Scale running on DC/OS and have set up a workspace, job-type, recipe-type and strike.

When I drop a file into the workspace area which is located at /vagrant/share/products/test.txt this file is then copied to /vagrant/share/products/ingesting/test.txt

However I am expecting only the first 10 bytes to be copied to the output directory. However it is not clear where this output directory is? 

I shall include my JSON files to set up Scale.

Also right at the end of this issue, you can see that the Strike is running from my dashboard.

POST /api/v4/workspaces/
```
{
"description": "Products",
"json_config": {
  "broker": {
    "type": "host",
    "host_path": "/vagrant/share/products"
  }
},
"name": "products",
"title": "Products",
"base_url": "http://m1.dcos:8090/products/",
"is_active": true
 }
```

POST /api/v4/job-types/
```
{
    "name": "read-bytes",
    "version": "1.0.0",
    "title": "Read Bytes",
    "description": "Reads x bytes of an input file and writes to output dir",
    "category": "testing",
    "author_name": "John_Doe",
    "author_url": "http://www.example.com",
    "is_operational": true,
    "icon_code": "f27d",
    "docker_privileged": true,
    "docker_image": "geoint/read-bytes",
    "priority": 230,
    "timeout": 3600,
    "max_scheduled": null,
    "max_tries": 3,
    "cpus_required": 1.0,
    "mem_required": 1024.0,
    "disk_out_const_required": 0.0,
    "disk_out_mult_required": 0.0,
    "interface": {
        "output_data": [
            {
                "media_type": "application/octet-stream",
                "required": true,
                "type": "file",
                "name": "output_file"
            }
        ],
        "shared_resources": [],
        "command_arguments": "10 ${input_file} ${job_output_dir}",
        "input_data": [
            {
                "media_types": [
                    "application/octet-stream"
                ],
                "required": true,
                "partial": true,
                "type": "file",
                "name": "input_file"
            }
        ],
        "version": "1.1",
        "command": ""
    },
    "error_mapping": {
        "version": "1.0",
        "exit_codes": {}
    },
    "trigger_rule": null
}
```

POST /api/v4/recipe-types/
```
{
    "definition": {
        "input_data": [
            {
                "media_types": [
                    "application/octet-stream"
                ],
                "name": "input_file",
                "required": true,
                "type": "file"
            }
        ],
        "jobs": [
            {
                "dependencies": [],
                "job_type": {
                    "name": "read-bytes",
                    "version": "1.0.0"
                },
                "name": "read-bytes",
                "recipe_inputs": [
                    {
                        "job_input": "input_file",
                        "recipe_input": "input_file"
                    }
                ]
            }
        ]
    },
    "description": "Read x bytes from input file and save in output dir",
    "name": "read-byte-recipe",
    "title": "Read Byte Recipe",
    "trigger_rule": {
        "configuration": {
            "condition": {
                "data_types": [],
                "media_type": ""
            },
            "data": {
                "input_data_name": "input_file",
                "workspace_name": "products"
            }
        },
        "is_active": true,
        "name": "read-byte-trigger",
        "type": "INGEST"
    },
    "version": "1.0.0"
}
```

POST /api/v4/strikes/
```
{
  "name": "products-strike-process",
  "title": "products-strike-process",
  "description": "products-strike-process",
  "configuration": {
    "version": "2.0",
    "workspace": "products",
    "monitor": {
      "type": "dir-watcher",
      "transfer_suffix": "_tmp"
      },
      "files_to_ingest": [
        {
          "filename_regex": ".*",
          "data_types": [
            "all_my_mounted_files"
          ]
        }
      ]
   }
}

```

In this screen grab below where my mouse pointer is, you can see that the strike is running which indicates why my test.txt was copied from the products/ directory and into the products/ingesting/ directory.

![scalestrikerunning](https://cloud.githubusercontent.com/assets/949809/20824987/e99e59b8-b8b0-11e6-9d53-6890de035cc9.png)

Here is the basic recipe that I have loaded based on the quick start example.

![recipedash](https://cloud.githubusercontent.com/assets/949809/20825068/8385734a-b8b1-11e6-8a51-8d0680688dfc.png)

Here is the job type also loaded into scale based on the quick start example.

![jobtypes](https://cloud.githubusercontent.com/assets/949809/20825093/afb60e48-b8b1-11e6-837c-c227803ba23b.png)

Also here is a screen dump of the workspace

![scaleworkspaces](https://cloud.githubusercontent.com/assets/949809/20825103/c295d156-b8b1-11e6-9bd9-9a0b4ee75bcf.png)

**Comment by gisjedi** [comment]
@soccerjustinh1 Your output workspace is defined in trigger rule under the recipe type definition:

```
    "trigger_rule": {
        "configuration": {
            "condition": {
                "data_types": [],
                "media_type": ""
            },
            "data": {
                "input_data_name": "input_file",
                "workspace_name": "products"
            }
        },
        "is_active": true,
        "name": "read-byte-trigger",
        "type": "INGEST"
    }
```

Strike defines your input workspace as 'product' and the recipe type defines your workspace as the same, which means your output files show up under `/vagrant/share/products` under the tree structure format scale uses to organize products.  It is of the form:

/recipe-name/recipe-version/job-name/job-version/YYYY/mm/dd/job-exe-number/

You should see this tree under `/vagrant/share/products` and the output will be there.

**Comment by soccerjustinh1** [comment]
@gisjedi Thanks for all your help so far I have now **successfully** pushed some data through **Scale**!

The reason I could not get the data through was that scale-ingest job required an agent with 5120MB of RAM however none of my agents had this available. So I needed to spin up an agent with 8GB  of RAM and I managed to get the read-bytes demo to run within Scale. I was trying to restrict the amount of RAM but now I have a machine with 200G of RAM so I can bump up the agents.

Only problem is that Scale dumps the (correct) results into the following directory not into my workspaces directory.

```
/var/lib/docker/volumes/scale_1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002_64_output_data/
```

I can see the data in the above directory is correct. So I am happy with that.

The geoint/scale:4.0.0 docker container that fails with an exit code (1) has the arguments `scale_post_steps -i 64`.

Because this does not exit cleanly then I cant get a _green traffic light_ on the _dashboard_ for Scale.

So it looks like scale is trying to run some steps at the end that copies the data out of the docker volume and back into the workspace area and that is failing.

@gisjedi Any ideas for a good place to look to get this **final** step to run cleanly?

![redtrafficreadbytes](https://cloud.githubusercontent.com/assets/949809/20911622/f2e61578-bbb8-11e6-87e6-a9e405973be1.png)

Here is the docker inspection of the final container that does not exit cleanly

```
[
    {
        "Id": "8e218d4ba9daa0286257b661735cad79e194b6b7104ed31240736730c3c72662",
        "Created": "2016-12-06T02:40:58.084752093Z",
        "Path": "./entryPoint.sh",
        "Args": [
            "scale_post_steps",
            "-i",
            "64"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2016-12-06T02:40:58.282955629Z",
            "FinishedAt": "2016-12-06T02:40:58.509408827Z"
        },
        "Image": "sha256:56594f45ad16047c285ec9f3263aa240bf2b33d70f80194f93cb0a25f2ee21fe",
        "ResolvConfPath": "/var/lib/docker/containers/8e218d4ba9daa0286257b661735cad79e194b6b7104ed31240736730c3c72662/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8e218d4ba9daa0286257b661735cad79e194b6b7104ed31240736730c3c72662/hostname",
        "HostsPath": "/var/lib/docker/containers/8e218d4ba9daa0286257b661735cad79e194b6b7104ed31240736730c3c72662/hosts",
        "LogPath": "",
        "Name": "/mesos-1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-S7.da4315b9-8668-429a-a5ea-f647257b2da9",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/lib/mesos/slave/slaves/1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-S7/frameworks/1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002/executors/64_post/runs/da4315b9-8668-429a-a5ea-f647257b2da9:/mnt/mesos/sandbox",
                "scale_1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002_64_output_data:/scale/output_data:ro",
                "/vagrant/share/products/:/scale/workspace_mounts/products:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "syslog",
                "Config": {
                    "syslog-address": "tcp://scale-logstash.marathon.mesos:9229",
                    "tag": "scale_64_post"
                }
            },
            "NetworkMode": "bridge",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 1024,
            "Memory": 1073741824,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 2147483648,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay/304ee903305c7c23f1f5758a47ec1196ae24efa6e07a0c66a243ac7f16cf75b0/root",
                "MergedDir": "/var/lib/docker/overlay/53fd6039218380d30ee6e8f33865cb54ccdde8f565d7971536d19afc078cd3d7/merged",
                "UpperDir": "/var/lib/docker/overlay/53fd6039218380d30ee6e8f33865cb54ccdde8f565d7971536d19afc078cd3d7/upper",
                "WorkDir": "/var/lib/docker/overlay/53fd6039218380d30ee6e8f33865cb54ccdde8f565d7971536d19afc078cd3d7/work"
            }
        },
        "Mounts": [
            {
                "Source": "/var/lib/mesos/slave/slaves/1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-S7/frameworks/1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002/executors/64_post/runs/da4315b9-8668-429a-a5ea-f647257b2da9",
                "Destination": "/mnt/mesos/sandbox",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "scale_1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002_64_output_data",
                "Source": "/var/lib/docker/volumes/scale_1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-0002_64_output_data/_data",
                "Destination": "/scale/output_data",
                "Driver": "local",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/vagrant/share/products",
                "Destination": "/scale/workspace_mounts/products",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "8e218d4ba9da",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5051/tcp": {},
                "80/tcp": {},
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "LIBPROCESS_IP=192.168.65.151",
                "MESOS_SANDBOX=/mnt/mesos/sandbox",
                "MESOS_CONTAINER_NAME=mesos-1be62a9c-fa4f-495b-8c53-c5c2c82d1a91-S7.da4315b9-8668-429a-a5ea-f647257b2da9",
                "SCALE_ELASTICSEARCH_URLS=http://10.0.2.15:1025",
                "SCALE_DB_NAME=scale",
                "SCALE_DB_USER=scale",
                "SCALE_DB_PASS=scale",
                "SCALE_DB_HOST=scale-db.marathon.mesos",
                "SCALE_DB_PORT=21692",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "scale_post_steps",
                "-i",
                "64"
            ],
            "Image": "geoint/scale:4.0.0",
            "Volumes": null,
            "WorkingDir": "/opt/scale",
            "Entrypoint": [
                "./entryPoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "build-date": "20160906",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "700f125ded1ce15be98499905a2e36415aad215f00561851d400f6aab4bfeb99",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/700f125ded1c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a6ebae7e81277b97bf3fcfba47e47b4fd04ea4f49bdf3e2566b8f5935f6b4d3e",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]


```

**Comment by soccerjustinh1** [comment]
@gisjedi  Looking a little deeper it seems like the common error for the container that is trying to run the scale_post_steps I get the following from stderr within this container.

Any ideas what is going wrong here?

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/scale/scale/local_settings.py", line 36, in <module>
    sniffer_timeout=60
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 169, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 126, in __init__
    self.sniff_hosts(True)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 250, in sniff_hosts
    node_info = self._get_sniff_data(initial)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 213, in _get_sniff_data
    raise TransportError("N/A", "Unable to sniff hosts.")
elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts.')
```

**Comment by gisjedi** [comment]
@soccerjustinh1 The exception you are seeing is a result of Scale being unable to communicate with Elasticsearch. The Scale post step has to look at the logs of the job to parse information out and it is failing to communicate with the Elasticsearch nodes. If you look at the Elasticsearch cluster running in DC/OS are all 3 tasks running? You can find this UI at http://m1.dcos/service/elasticsearch/

**Comment by soccerjustinh1** [comment]
@gisjedi Yes you are correct! I had the elasticsearch cluster with only 3 of the agents provisioned.

![elasticsearch](https://cloud.githubusercontent.com/assets/949809/20996376/1b76f0da-bd4d-11e6-8e50-8950f9c1de15.png)

Increased the provisioning to 6
![increasescaling](https://cloud.githubusercontent.com/assets/949809/20996394/2e296e38-bd4d-11e6-9c18-ecddb018124e.png)

Now I get all 6 on the Elasticsearch dashboard
![elasticsearchincreased](https://cloud.githubusercontent.com/assets/949809/20996400/3c4a9b2c-bd4d-11e6-9fe8-28388c484faf.png)

Now Scale Dashboard recipe passed.
![passingrecipe](https://cloud.githubusercontent.com/assets/949809/20996410/4ce67820-bd4d-11e6-98da-68e8ef2672bb.png)

And I can look at the recipe results
![workingproducts](https://cloud.githubusercontent.com/assets/949809/20996416/5be97250-bd4d-11e6-9d77-bebe84a581f6.png)
